# Generated by Django 4.2.25 on 2026-01-05 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fasting_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField(choices=[(18, '18-hours'), (24, '24-hours'), (36, '36-hours')], default=18)),
                ('monday_plan', models.TextField()),
                ('tuesday_plan', models.TextField()),
                ('wednesday_plan', models.TextField()),
                ('thursday_plan', models.TextField()),
                ('friday_plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
