# Generated by Django 4.2.25 on 2026-01-06 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fastblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasting_plan',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fasting_plan',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasting_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
