# Generated by Django 4.2.25 on 2026-01-06 16:34

from django.db import migrations # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('fastblog', '0003_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fasting_plan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-created_at']},
        ),
    ]
